- name: install HAProxy
  package: name=haproxy

- name: put HAProxy config
  template: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg

- name: enable and start HAProxy
  service: name=haproxy state=started enabled=yes
